import type { PreviewControlSpec } from './types.js';

/** Force preview sidebar controls — single TS authority (was hardcoded in force-viewer HTML). */
export const FORCE_PREVIEW_PARAM_SPECS: PreviewControlSpec[] = [
  {
    key: 'link_distance',
    label: 'Link distance',
    group: 'Simulation',
    kind: 'number',
    defaultValue: '256',
    min: 10,
    max: 500,
    step: 10,
    persistNamespace: 'simulation',
  },
  {
    key: 'link_strength',
    label: 'Link strength',
    group: 'Simulation',
    kind: 'number',
    defaultValue: '0.08',
    min: 0,
    max: 2,
    step: 0.05,
    persistNamespace: 'simulation',
  },
  {
    key: 'charge_strength',
    label: 'Charge strength',
    group: 'Simulation',
    kind: 'number',
    defaultValue: '-900',
    min: -1000,
    max: 0,
    step: 10,
    persistNamespace: 'simulation',
  },
  {
    key: 'collision_padding',
    label: 'Collision padding',
    group: 'Simulation',
    kind: 'number',
    defaultValue: '24',
    min: 0,
    max: 100,
    step: 2,
    persistNamespace: 'simulation',
  },
  {
    key: 'velocity_decay',
    label: 'Velocity decay',
    group: 'Simulation',
    kind: 'number',
    defaultValue: '0.34',
    min: 0,
    max: 1,
    step: 0.05,
    persistNamespace: 'simulation',
  },
  {
    key: 'alpha_min',
    label: 'Alpha min',
    group: 'Simulation',
    kind: 'number',
    defaultValue: '0.006',
    min: 0,
    max: 0.1,
    step: 0.001,
    persistNamespace: 'simulation',
  },
  {
    key: 'alpha_decay',
    label: 'Alpha decay',
    group: 'Simulation',
    kind: 'number',
    defaultValue: '0.0228',
    min: 0,
    max: 0.1,
    step: 0.001,
    persistNamespace: 'simulation',
  },
  {
    key: 'curve_handle_ratio',
    label: 'Curve handle ratio',
    group: 'Render',
    kind: 'number',
    defaultValue: '0.35',
    min: 0,
    max: 1,
    step: 0.05,
    persistNamespace: 'render',
  },
];
