/**
 * M5: Shared parity test fixtures.
 *
 * Each fixture contains a serialized Frame tree (post-loader defaults) and
 * expected placed coordinates generated by the TS engine with MockTextAdapter
 * under spec 011 text-layout defaults (max_width_chars: 66).
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { layoutFrameTree } from '../src/layout.js';
import { MockTextAdapter } from '../src/text-measure.js';
import { buildFrame, collectBounds, type FixtureBounds } from './parity-fixture-builder.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface Fixture {
  name: string;
  description: string;
  root: Record<string, unknown>;
  expected: {
    width: number;
    height: number;
    bounds: Record<string, FixtureBounds>;
  };
}

const fixturesPath = resolve(__dirname, 'fixtures', 'parity-fixtures.json');
const fixtures: Fixture[] = JSON.parse(readFileSync(fixturesPath, 'utf-8'));

const adapter = new MockTextAdapter();

describe('parity fixtures', () => {
  for (const fixture of fixtures) {
    describe(fixture.name, () => {
      const root = buildFrame(fixture.root);
      const result = layoutFrameTree(root, adapter);
      const bounds = collectBounds(root);

      it(`overall size: ${fixture.expected.width}×${fixture.expected.height}`, () => {
        expect(result.width).toBe(fixture.expected.width);
        expect(result.height).toBe(fixture.expected.height);
      });

      for (const [frameId, expected] of Object.entries(fixture.expected.bounds)) {
        it(`${frameId}: (${expected.x}, ${expected.y}) ${expected.w}×${expected.h}`, () => {
          const actual = bounds[frameId];
          expect(actual, `frame "${frameId}" not found in layout output`).toBeDefined();
          expect(actual!.x).toBeCloseTo(expected.x, 0);
          expect(actual!.y).toBeCloseTo(expected.y, 0);
          expect(actual!.w).toBeCloseTo(expected.w, 0);
          expect(actual!.h).toBeCloseTo(expected.h, 0);
        });
      }
    });
  }
});
